### ISSUE TITLE
[React Native] ReferenceError: Can't find variable: WebAssembly

### ISSUE THREAD

**Issue by starpl** [morfix-io/node-seal#105]
After I've created fresh project with 
`npx react-native init project-name --template react-native-template-typescript`
and installing react-native-get-random-values + adding
`global.document = {}`
into the code, I'm constantly getting this error: **Possible Unhandled Promise Rejection (id: 0):
ReferenceError: Can't find variable: WebAssembly**

I'm currently developing on Windows; I've tried to install react-native-wasm, which doesnt work also (complains about not finding react-native-wasm/src/index.js, which exists)

package.json:
```
{
  "name": "project-name",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "node-seal": "^4.5.5",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-get-random-values": "^1.7.0",
    "react-native-wasm": "^0.1.3"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.20",
    "@types/react-native": "^0.64.0",
    "@types/react-test-renderer": "^16.9.2",
    "babel-jest": "^26.6.3",
    "eslint": "^7.14.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.64.0",
    "react-test-renderer": "17.0.1",
    "typescript": "^3.8.3"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

Maybe Windows is the main issue, but I'm not sure.
How to fix this? Any ideas?

UPD: also there is a warning **no native wasm support detected** that appears before promise gets rejected

**Comment by starpl** [comment]
same error on linux

installing react-native-wasm on linux gives different warning
![image](https://user-images.githubusercontent.com/41567356/118352211-d2a22500-b568-11eb-895f-909a604c6a9e.png)
though I'm not sure that it's worth to discuss this here, it's not related to main problem I think

**Comment by starpl** [comment]
also, if you use node-seal implementation "throws_js_web_umd" - complains about heap oversize, "throws_wasm_node_umd(es)" - doesnt work either

**Comment by s0l0ist** [comment]
I started to investigate what is going on. It looks like when developing on Mac, it works in the iOS simulator, but when ran on a physical device it fails with the error you mentioned about WebAssembly. Long story short, WASM is not supported (limitation of the underlying implementation of react-native) and I need to update the docs.

The JS variants should work. I've found that react-native will crash with a heap size exception when trying to compile/pack the library. I was eventually able to get it working by overriding nodes max-old-space-size. However, in practice the JS variants are far too slow to do anything meaningful past polymodulus degree greater than 2048. 

A solution for which I don't have an explicit example, but one that would work is to load a hidden WebView that instantiates node-seal's WASM build. To interact with the webview, you need to build a communication layer with the WebView to pass commands and serialized messages back and forth.

I've done this work with another project that uses WASM so it is definitely possible. If I'm able to make the work public, I will post it as a reference. 

You're basically formulating a work around by communicating with node-seal in a separate browser context which is independent of your application.

**Comment by s0l0ist** [comment]
I thought I would follow up here with an example taken from another open-source repo I previously worked on. This uses a [PSI library](https://github.com/OpenMined/PSI) that I co-authored. It is compiled to WebAssembly using emscripten much in the same way as `node-seal`.

I use a [WebView](https://github.com/react-native-webview/react-native-webview) to load a hidden browser and expose a basic API for sending messages across the WebView boundary. It isn't visible to the UI because I've set the style to be `0` for height and width. To use it effectively in all components, I use a [context](https://github.com/s0l0ist/PriCal/blob/main/components/contexts/PsiContext.tsx)
and corresponding [provider](https://github.com/s0l0ist/PriCal/blob/main/components/providers/PsiProvider.tsx).

I needed to create a protocol for sending and receiving messages between the main application and the WebView. I exposed this using the [usePsiProtocol](https://github.com/s0l0ist/PriCal/blob/main/hooks/usePsiProtocol.tsx) hook. The hook waits for the WASM library to finish loading before it is ready to send messages.

The WebView communicates with a static site that I've built. It is bundled/minified with inlined JS and stored in the [assets folder](https://github.com/s0l0ist/PriCal/tree/main/assets/www). I can then serve it within the React Native application (WebView) without needing to host a server.

The repo for the static site is [PriCal-WWW](https://github.com/s0l0ist/PriCal-WWW). It includes hooks to manage messages received and also has a config to bundle/minify/inline JS.

Hope this helps.
