### ISSUE TITLE
How can i use global context (different seal)

### ISSUE THREAD

**Issue by eakeakarat** [morfix-io/node-seal#122]
### Here is my init code:
    async function contextInit() {
        const SEAL = require('node-seal')
        const seal = await SEAL()
        
        const schemeType = seal.SchemeType.bfv
        const securityLevel = seal.SecurityLevel.tc128
        const polyModulusDegree = 4096
        const bitSizes = [36, 36, 37]
        const bitSize = 20
        
        const encParms = seal.EncryptionParameters(schemeType)
        encParms.setPolyModulusDegree(polyModulusDegree)
        encParms.setCoeffModulus(seal.CoeffModulus.Create(polyModulusDegree, Int32Array.from(bitSizes)))
        encParms.setPlainModulus(seal.PlainModulus.Batching(polyModulusDegree, bitSize))
        
        const context = seal.Context(encParms, true, securityLevel)
        
        if (!context.parametersSet()) {
            throw new Error('Could not set the parameters in the given context. Please try different encryption parameters.')
        }
        return context
    }
    module.exports.context = contextInit()
### 

### And call context like this:
    (async () => {
        const SEAL = require('node-seal')
        const seal = await SEAL()
        const context = await require('./main').context

        const key = seal.KeyGenerator(context)

    })()
###
### But i'm got an blind error 
    BindingError: Expected null or instance of SEALContext, got an instance of SEALContext
###

###
    It's can use context(create from another seal) with another seal ?
###

**Comment by s0l0ist** [comment]
Short answer:
You cannot `require('node-seal')` more than once in an application -- your application should only require it once.

Long answer:
This isn't working because every time you do `require('node-seal')` you're creating a new WebAssembly instance of the library where all seal objects are created in web assembly memory. The first time you create the context, that instance lives in its own isolated wasm memory (we will call this wasm_a).

The moment you try to run the following:
```javascript
(async () => {
    const SEAL = require('node-seal') // wasm_a
    const seal = await SEAL()
    const context = await require('./main').context // wasm_b

    const key = seal.KeyGenerator(context)
})()
```
You create a second instance of node-seal with its own memory, call it wasm_a. The `context` is a javascript object, but inside it holds a reference to the memory location inside the web assembly container's memory. The library complains when you're trying to load the object from wasm_b into wasm_a, but neither of them is aware nor can reference each other's memory.

**Comment by s0l0ist** [comment]
Closing because this is not an issue with `node-seal`, but more of how to use WebAssembly imports. Please feel free to keep posting questions if you have any.
