### ISSUE TITLE
localhost:8080 says TypeError: Cannot read property 'BFV' of undefined

### ISSUE THREAD

**Issue by miaaaahmed97** [morfix-io/node-seal#74]
I get a error in the browser dialog box that says:

`TypeError: Cannot read property 'BFV' of undefined`

this is the only part of the code that has BFV:

```
const parms = Morfix.EncryptionParameters({
            schemeType: Morfix.SchemeType.BFV
        })
```

can you help me out ?

**Comment by s0l0ist** [comment]
The way to initialize parameters has changed over the last few releases. Unfortunately, it will require you to use pass in parameters directly instead of passing an object with key/value pairs. 

Provided you have already imported and initialized the library, you would simple call the function and pass in the argument directly:

```
const parms = Morfix.EncryptionParameters(Morfix.SchemeType.BFV)
```

More information can be found in the examples pointed to in the readme.
