### ISSUE TITLE
[Feature Request] Typescript definitions

### ISSUE THREAD

**Issue by AZMCode** [morfix-io/node-seal#87]
Pretty self explanatory. It'd be awesome to have .d.ts for the project. This would also open up usage in deno.

**Comment by AZMCode** [comment]
Working on it, but have no idea where to place it within the project structure.
https://gist.github.com/AZMCode/52413c2c8bb4a9b232cd418a3069f451

**Comment by AZMCode** [comment]
Actually, considering the project uses JSDoc annotations, there should be a way to generate .d.ts typings from that. I tried myself but couldn't get them to work.

**Comment by s0l0ist** [comment]
Thanks for your feedback. I'll try and get something up and working over the next few days/weeks.

The JSDoc shouldn't be relied upon for this as there were some issues I faced.

**Comment by s0l0ist** [comment]
@AZMCode, I've since re-written the entire library in TypeScript. 

Please install the latest release, but please note the deep-import link paths have changed, check out the [readme](https://github.com/morfix-io/node-seal/blob/master/README.md). The good news is that the bundles have declaration files. Let me know if this doesn't work.

**Comment by AZMCode** [comment]
Wow. Appreciate it hugely.

**Comment by s0l0ist** [comment]
No prob! I figured it was time anyway for it to move to TS.

I wasn't able to get it working in deno. I think there are some issues with emscripten's output which deno doesn't like. Deno doesn't support `utf-16le` just yet so it probably won't happen for a while unless I can figure out how to bundle all the TS together.
