### ISSUE TITLE
Actual SIMD utilization?

### ISSUE THREAD

**Issue by ibsusu** [morfix-io/node-seal#98]
Heya, I understand that you're working on this with [SIMD](https://github.com/morfix-io/node-seal/blob/3b3b5b140dd43e68e1cb1326b249b8efbe877fb4/src/implementation/encryption-parameter-qualifiers.ts#L131) in mind so considering that SIMD is coming to webassembly in Chrome and Firefox are you going to implement it or has it already been done?

https://www.chromestatus.com/feature/6533147810332672

**Comment by s0l0ist** [comment]
@ibsusu, the comments for almost all the functions/properties are taken from their source code.

SEAL has support for SIMD, but there are no direct modifications to the SEAL source that have been optimized for WASM SIMD. Instead, any WASM SIMD optimization is done by the compiler (emscripten) by providing the `-msimd128` flag. However, enabling the flag `-msimd128` causes the library to be slower for several HE functions. I have not identified the root cause, but I suspect some answers reside in [clang.h](https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/clang.h).

Because of this bug, I don't ship a SIMD build.

**Comment by ibsusu** [comment]
I wish I saw the reply earlier, do you think it would be worth it to run the benchmarks on a canary build of chrome?
